// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Fm_7OTJ9CGL5uag0Z1LaUoV3tZpjxPE',
    appId: '1:912402332756:web:1a79f0482717a2adf001c1',
    messagingSenderId: '912402332756',
    projectId: 'kt-mg-textile-calculator',
    authDomain: 'kt-mg-textile-calculator.firebaseapp.com',
    storageBucket: 'kt-mg-textile-calculator.appspot.com',
    measurementId: 'G-P7FZS2KHQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCliqraqZPTFQfunPkyJBn11HRKoXEsYxI',
    appId: '1:669571586292:android:14b663e945d122962ba6a1',
    messagingSenderId: '669571586292',
    projectId: 'mg-textile-calculator',
    storageBucket: 'mg-textile-calculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0PsgCaosuv63xl-rcJckYBz1XTk-pbWE',
    appId: '1:912402332756:ios:63baaa9a41289e65f001c1',
    messagingSenderId: '912402332756',
    projectId: 'kt-mg-textile-calculator',
    storageBucket: 'kt-mg-textile-calculator.appspot.com',
    iosBundleId: 'com.mg.cotton.textile.calculator.kt.one.own.mgCottonTextileCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0PsgCaosuv63xl-rcJckYBz1XTk-pbWE',
    appId: '1:912402332756:ios:63baaa9a41289e65f001c1',
    messagingSenderId: '912402332756',
    projectId: 'kt-mg-textile-calculator',
    storageBucket: 'kt-mg-textile-calculator.appspot.com',
    iosBundleId: 'com.mg.cotton.textile.calculator.kt.one.own.mgCottonTextileCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Fm_7OTJ9CGL5uag0Z1LaUoV3tZpjxPE',
    appId: '1:912402332756:web:260e2260e2ebfb36f001c1',
    messagingSenderId: '912402332756',
    projectId: 'kt-mg-textile-calculator',
    authDomain: 'kt-mg-textile-calculator.firebaseapp.com',
    storageBucket: 'kt-mg-textile-calculator.appspot.com',
    measurementId: 'G-FFGMV1YX2F',
  );

}