// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKXR-8FgwAFhIlFhe-AUhTyxny4M1PdSU',
    appId: '1:669571586292:web:5f48c9e53568ad812ba6a1',
    messagingSenderId: '669571586292',
    projectId: 'mg-textile-calculator',
    authDomain: 'mg-textile-calculator.firebaseapp.com',
    storageBucket: 'mg-textile-calculator.appspot.com',
    measurementId: 'G-DJZY27RPJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCliqraqZPTFQfunPkyJBn11HRKoXEsYxI',
    appId: '1:669571586292:android:14b663e945d122962ba6a1',
    messagingSenderId: '669571586292',
    projectId: 'mg-textile-calculator',
    storageBucket: 'mg-textile-calculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0gswF8msW4XuM2Yd9x06nbKREToelKzg',
    appId: '1:669571586292:ios:6b5cc658301e3a2c2ba6a1',
    messagingSenderId: '669571586292',
    projectId: 'mg-textile-calculator',
    storageBucket: 'mg-textile-calculator.appspot.com',
    androidClientId: '669571586292-i8rp0qjg42dqbv274io4ag0canka61f2.apps.googleusercontent.com',
    iosClientId: '669571586292-728i0iebq73r205hp36hgansdv0jknut.apps.googleusercontent.com',
    iosBundleId: 'com.mg.cotton.textile.calculator.kt.one.own.mgCottonTextileCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0gswF8msW4XuM2Yd9x06nbKREToelKzg',
    appId: '1:669571586292:ios:6b5cc658301e3a2c2ba6a1',
    messagingSenderId: '669571586292',
    projectId: 'mg-textile-calculator',
    storageBucket: 'mg-textile-calculator.appspot.com',
    androidClientId: '669571586292-i8rp0qjg42dqbv274io4ag0canka61f2.apps.googleusercontent.com',
    iosClientId: '669571586292-728i0iebq73r205hp36hgansdv0jknut.apps.googleusercontent.com',
    iosBundleId: 'com.mg.cotton.textile.calculator.kt.one.own.mgCottonTextileCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKXR-8FgwAFhIlFhe-AUhTyxny4M1PdSU',
    appId: '1:669571586292:web:1c4eaa0a39ef38932ba6a1',
    messagingSenderId: '669571586292',
    projectId: 'mg-textile-calculator',
    authDomain: 'mg-textile-calculator.firebaseapp.com',
    storageBucket: 'mg-textile-calculator.appspot.com',
    measurementId: 'G-F4CEEJ887T',
  );
}
